baseurl = "https://kenjiadachi.github.io/my-portfolio/"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "だちけんのブログ"
theme = "hugo-theme-dream"
# パスの指定。これをしないとcssがうまく反映されません。
canonifyurls = true

# copyright = ""

googleAnalytics = "UA-80233037-7"
disqusShortname = "dachiken"

enableRobotsTXT = true

[params]
  background = "black"
  linkColor = "seagreen"

  author = "だちけん"
  # description = ""
  avatar = "/images/avatar.png"
  motto = "今年の目標はおせっかいになること"

  # email = "kenji.183927@gmail.com"
  # github = ""
  # linkedin = ""
  # codepen = ""
  # stackoverflow = ""

  siteStartYear = 2020

  # favicon = "/favicon.ico"

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true
  dark404Button = true
