baseurl = "https://kenjiadachi.github.io/my-portfolio/"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "だちけん"
theme = "hugo-theme-dream"
disqusShortname = "dachiken"

# copyright = ""

# googleAnalytics = ""

# disqusShortname = ""

# enableRobotsTXT = true

[params]
  background = "black"
  # backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  author = "だちけん"
  # description = ""
  avatar = "/images/avatar.png"
  motto = "今年の目標はおせっかいになること"

  email = "kenji.183927@gmail.com"
  # github = ""
  # linkedin = ""
  # codepen = ""
  # stackoverflow = ""

  siteStartYear = 2020

  # favicon = "/favicon.ico"

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true
  dark404Button = true
